name: CD

on:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install
              run: yarn install
            - name: Install peers
              run: yarn run install-peers
            - name: Lint
              run: yarn run lint
            - name: Test
              run: yarn run test
            - name: Build
              run: yarn run build
            - name: Publish
              run: yarn semantic-release
